name: Node.js CI

on:
  push:
    branches: [ steja1439-patch-1 ]
  pull_request:
    branches: [ steja1439-patch-1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
