// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlzxzwotnqtzcewffnmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impsenh6d290bnF0emNld2Zmbm1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDIxODMsImV4cCI6MjA2NjMxODE4M30.Ie9gCD8XCYPnsP8XclptUAgtiWP3Vmd_itV4bIztkEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);